name: Tailscale

on:
  push:
    branches: [ "main" ]

jobs:
  delete_devices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Tailscale API Key
        run: echo "TAILSCALE_API_KEY=${{ secrets.TAILSCALE_API_KEY }}" >> $GITHUB_ENV

      - name: SSH into EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            tailscale status --json | jq -r '.Peer | to_entries[] | select(.value.HostName | contains("github-fv")) | .value.ID'
