name: Tailscale

on:
  push:
    branches: [ "main" ]

jobs:
  delete_devices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Tailscale API Key
        run: echo "TAILSCALE_API_KEY=${{ secrets.TAILSCALE_API_KEY }}" >> $GITHUB_ENV

      - name: SSH into EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Get device IDs
            device_ids=$(tailscale status --json | jq -r '.Peer | to_entries[] | select(.value.HostName | contains("github-fv")) | .value.ID')

            # Iterate over device IDs and delete each device
            for device_id in $device_ids; do
              # Delete device
              response=$(curl -s -X DELETE "https://api.tailscale.com/api/v2/device/$device_id" -u "$TAILSCALE_API_KEY:")
              if [[ $response == *"cannot delete devices outside of your tailnet"* ]]; then
                echo "Cannot delete device $device_id: Device does not belong to your tailnet"
              else
                echo "Deleted device $device_id"
              fi
            done
